# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Leiserson
email: max.leiserson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Mark (Max) Leiserson: computer scientist, computational biologist, cancer research. Post-doc at Microsoft Research and future faculty at Maryland College Park.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxleiserson.com" # the base hostname & protocol for your site
twitter_username: maxleiserson
github_username:  mdml

# Build settings
markdown: kramdown
